### ISSUE TITLE
Windows features window is blank on windows 8+

### ISSUE THREAD

**Issue by amitxv** [amitxv/EVA#22]
Removing ``defender`` related files in debloat.sh results in a empty windows features window on windows 8+, although this is not that much of a problem as we configure this before running the debloat.sh script in linux and is rarely reconfigured once set up.

https://github.com/amitxv/EVA/blob/aa2ecb30a2cfc4d4d83a9eae7ca5b516ee5a1834/debloat.sh#L51

![image](https://user-images.githubusercontent.com/86924251/180224687-36c627fb-6085-42b9-b219-7657298db504.png)

**Comment by nicklvh** [comment]
is it possible to disable features while this still being blank? i accidentally left windows media features on... not that big of a deal but would be nice to get rid of it

**Comment by Vojtazz** [comment]
> is it possible to disable features while this still being blank? i accidentally left windows media features on... not that big of a deal but would be nice to get rid of it

ResetBase may broke it on 1803 (if you are using it) 
try this command:
Disable-WindowsOptionalFeature –FeatureName "WindowsMediaPlayer" -Online

**Comment by amitxv** [comment]
This has been resolved in https://github.com/amitxv/EVA/commit/9a049a98c997c1c763e82862c75c7ef5032c42dc
