### ISSUE TITLE
Unable to run apply-registry

### ISSUE THREAD

**Issue by 70T** [amitxv/EVA#24]
When opening apply-registry from the command prompt, I receive the following errors:

`The program can't start because api-ms-win-core-file-l2-1-0.dll is missing from your computer.`
&
`The procedure entry point ucrtbase.terminate could not be located in the dynamic link library api-ms-win-crt-runtime-l1-1-0.dll.`

I am on a fresh W7 Service Pack 1 installation.

**Comment by amitxv** [comment]
Did you integrate the updates listed [here](https://github.com/amitxv/EVA/blob/main/docs/building.md#integrating-updates)? If you built the binary yourself, what python version did you use?

**Comment by 70T** [comment]
I ended up redoing my installation as I had overlooked the build section, which was my fault, though the apply-registry file threw me the same errors afterwards.

**Comment by amitxv** [comment]
Did you integrate all of the recommended updates?

If you built the program yourself please note that python 3.8.6 is the last version to support windows 7

**Comment by amitxv** [comment]
Can you try the [new binary](https://github.com/amitxv/EVA/tree/main/prerequisites/scripts/registry) and let me know if the persists?
