### ISSUE TITLE
Librewolf Web Installer Installation Issue

### ISSUE THREAD

**Issue by runninghamster0** [amitxv/EVA#25]
There seems to be an issue with the setup downloaded by the Librewolf web installer, where upon installation it detects an existing instance of Librewolf is running. Pressing the OK button kills the setup.

![snip.png](https://user-images.githubusercontent.com/52240313/180626715-72373414-aac6-4aec-a309-b824fa8068f9.png)

Installing Librewolf by downloading the setup from the website doesn't show the same issue.

**Comment by Vojtazz** [comment]
I have this issue too.

**Comment by amitxv** [comment]
I was able to fix reproduce and fix this error by using the original filename when downloading the binary. Can you try the [new script](https://github.com/amitxv/EVA/blob/main/prerequisites/scripts/librewolf-web-installer.bat) and let me know if the installation succeeds?

**Comment by amitxv** [comment]
I was able to reproduce and fix this error by using the original filename when downloading the binary. Can you try the [new script](https://github.com/amitxv/EVA/blob/main/prerequisites/scripts/librewolf-web-installer.bat) and let me know if the installation succeeds?

**Comment by Vojtazz** [comment]
Confirmed, it works
