### ISSUE TITLE
Vcredits installation problem

### ISSUE THREAD

**Issue by Vojtazz** [amitxv/EVA#26]
There is an issue with launching vcredist, it has to be unpacked otherwise it can't be launched.

**Comment by Vojtazz** [comment]
(downloaded with your script)

**Comment by amitxv** [comment]
What error does it throw? A screenshot would be helpful. Running a file within a compressed file will automatically be extracted to the temp folder anyway

**Comment by Vojtazz** [comment]
File is placed in vcredist/vcredist.zip or vcredist.zip in the temp file. In this zip there is exe file, which should run. It has to be extracted before.

**Comment by amitxv** [comment]
That does not explain the "problem" you mentioned, i assumed there was an error message. As i mentioned previously you do not need to extract a binary from a compressed file to run it if it has no dependencies within the compressed file because it will get extracted to the temp folder upon runtime
