### ISSUE TITLE
UAC issue

### ISSUE THREAD

**Issue by Vojtazz** [amitxv/EVA#29]
Sometime after using OS, uac got restored. Registry was applied correctly. I didn't change anything, I have to set EnableLua to 0 in registry to make it work. Also what about:

`"PromptOnSecureDesktop"`

`"ConsentPromptBehaviorAdmin"`

`"EnableSecureUIAPaths"`
@amitxv

**Comment by amitxv** [comment]
UAC can't change itself, you must have a program or something else interfering with it

What are the reasons for including each of those registry keys?

**Comment by Vojtazz** [comment]
are they necessary?

**Comment by amitxv** [comment]
You should know since you suggested them, i don't add registry keys if i don't have a reason to

**Comment by Vojtazz** [comment]
thanks.
