### ISSUE TITLE
Microsoft Edge grey/empty shortcut in start menu Windows 19044.1889

### ISSUE THREAD

**Issue by FeyrisTan** [amitxv/EVA#32]
Any way to get rid of it?

**Comment by amitxv** [comment]
It should get deleted after running the shell script in linux

**Comment by FeyrisTan** [comment]
It didn't. Does Windows 8+ include 10 as well or is Windows 8+ just windows 8 and 8.1 (in the instructions)?

**Comment by amitxv** [comment]
Windows 8+ includes Windows 8 and everything after that, what start menu are you talking about anyway? You should be able to delete the shortcut from OpenShell (right click -> open file location)

**Comment by FeyrisTan** [comment]
In Open-shell Microsoft Edge still exists under the "Apps" (metroapps) shortcut. Opening that location only opens "Applications" in file explorer and I can not do anything there. I know having an empty shortcut of microsoft edge that can't be deleted has been an issue for a while if improperly removed. Maybe I made a mistake somewhere. I search the ntlite forum for a bit.
