### ISSUE TITLE
how to ensure that there is no IRQ sharing on my system?

### ISSUE THREAD

**Issue by amymor** [amitxv/EVA#34]
you said:

> Ensure that there is no IRQ sharing on your system by checking win + r, msinfo32 Hardware Resources > Conflicts/Sharing section.

but how?
here is mine:
![image](https://i.imgur.com/BryMfI5.png )

Note: i have already enabled msi mode for all devices.

**Comment by amitxv** [comment]
That is fine. See an example for IRQ sharing [here](https://cpux.net/help/msinfo32/categories/hardware/conflicts-sharing) as an example

**Comment by amymor** [comment]
> That is fine. See an example for IRQ sharing [here](https://cpux.net/help/msinfo32/categories/hardware/conflicts-sharing) as an example

thanks, got it.
