### ISSUE TITLE
Qos policy is not displayed in Group Policy Editor

### ISSUE THREAD

**Issue by amymor** [amitxv/EVA#35]
![Untitled](https://user-images.githubusercontent.com/54497554/186254901-ea829226-f694-44e8-980a-93f121a4a44f.png)

1. as you see both policy created by your script and Atlas OS are not displayed in gpedit. i tried `gpupdate /force` but still same result.

2. i also noticed that your script uses path as value for `Application Name` while gpedit and Atlas just use name, does it make difference?

**Comment by amymor** [comment]
i tried to create a policy with gpedit again but this time i used RegFromApp (Nirsoft) to monitor gpedit activity, i noticed that gpedit adds this settings below to registry:

```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy Objects\{4FBAE66F-2986-4FE7-B762-E8018F7F3B28}Machine\SOFTWARE\Policies\Microsoft\Windows\QoS\hh]
"Version"="1.0"
"Application Name"="gg.exe"
"Protocol"="*"
"Local Port"="*"
"Local IP"="*"
"Local IP Prefix Length"="*"
"Remote Port"="*"
"Remote IP"="*"
"Remote IP Prefix Length"="*"
"DSCP Value"="46"
"Throttle Rate"="-1"

```
i saw something like it before (when tried to set some options through gpedit i noticed that gpedit adds its settings in another address in registry), so i guess thats fine. but still dont know why you use path instead of name? i think name is better because changing game location doesnt affect policy.

**Comment by amitxv** [comment]
That is normal, policies applied directly through registry do not reflect in gpedit.msc (a file does not get updated, i believe it was a .pol file) but they still work as long as the group policy service and the mup.sys driver are running. You can verify if the QoS policy is working with [this method](https://github.com/amitxv/EVA/blob/main/docs/research.md#how-can-you-verify-if-a-dscp-qos-policy-is-working)
