### ISSUE TITLE
Memory Cleaner link leads to 404

### ISSUE THREAD

**Issue by Zusier** [amitxv/EVA#4]
The portion about [danskee's memory cleaner](https://github.com/amitxv/EVA/blob/main/docs/post-install.md#memory-cleaner) leads to a 404. You could link to [MajorGeek's mirror of the binary](https://www.majorgeeks.com/files/details/memory_cleaner_danskee.html) or [my mirror and the source](https://git.zusier.xyz/Zusier/MemoryCleaner) as an alternative?

**Comment by amitxv** [comment]
The broken link is intentional as it is an official reference but i can provide your mirror and the source as an alternative
