### ISSUE TITLE
Suggestion: Use a compiled python script to execute python scripts from this repository.

### ISSUE THREAD

**Issue by Aetopia** [amitxv/EVA#63]
Source: https://github.com/Aetopia/PyOne-Onefile-Python-Interpreter

I was thinking if possible, replace the compiled python executables with a batch file which redirects to compiled python script (kind like a small runtime) which executes the scripts from this repository.

Advantages of doing this are:
1. Easier to push updates for any python script since you don't need to recompile each and every time.
2. The compiled script/runtime will have all of the dependencies required for the scripts.

**Comment by amitxv** [comment]
At that point, i may use Python portable as a onefile interpreter still requires re-building if new modules are used. I'm also considering rewriting the scripts in C++
