### ISSUE TITLE
Issue: Setting and syncing time automatically does not work

### ISSUE THREAD

**Issue by xyzze** [amitxv/EVA#68]
Syncing and setting time automatically does not work. Circle spins forever :D
![Screenshot (1)](https://user-images.githubusercontent.com/101590573/194719398-34931abf-12ca-44f0-8334-7f37b27c8ad0.png)

**Comment by amitxv** [comment]
It seems to be working fine for me with default services

![image](https://user-images.githubusercontent.com/86924251/194755978-1dadb254-a1bb-44c5-b936-0b32458e85a5.png)

Have you tried playing around with the following?

![image](https://user-images.githubusercontent.com/86924251/194756001-c2758a75-b6e0-42be-b39d-bf5d031e6a62.png)

**Comment by xyzze** [comment]
![image](https://user-images.githubusercontent.com/101590573/194757393-68cfa2e7-6ec2-4a47-aa8f-727e2c55bfc7.png)
Same situation, services are enabled. 22H2 same as yours

![image](https://user-images.githubusercontent.com/101590573/194757423-4be4546f-a45f-4908-8ce8-182701a98582.png)

**Comment by amitxv** [comment]
Most likely a Windows bug
