### ISSUE TITLE
FSE - FSO (Windows 10 1703+)

### ISSUE THREAD

**Issue by NotAspects** [amitxv/EVA#74]
By disabling FSO/FSE `reg.exe add "HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "!binary_path!" /t REG_SZ /d "~ DISABLEDXMAXIMIZEDWINDOWEDMODE" /f > null 2>&1. `

Performance will not be improved and it will create long Alt-tab, which is not pleasant for the game experience.

https://devblogs.microsoft.com/directx/demystifying-full-screen-optimizations/

You should add that by disabling this option Alt-Tab problems can appear so that people can fix this problem.

`choice /c yn /n /m "disable fullscreen optimizations?  [Black-screen Alt-Tab] (Windows 10 1703+ Only) [Y/N]"`

**Comment by amitxv** [comment]
A longer alt-tab time is an unreasonable justification for using legacy flip. The ~1 second black screen can be almost [completely eliminated with CRU](https://github.com/amitxv/EVA/blob/main/docs/post-install.md#configure-cru).
