### ISSUE TITLE
Use /Q argument to apply MSI Afterburner Settings at startup.

### ISSUE THREAD

**Issue by Aetopia** [amitxv/EVA#79]
https://github.com/amitxv/EVA/blob/main/docs/post-install.md#configure-msi-afterburner

Here, it is recommended to use a batch file to apply MSI Afterburner settings at startup but instead one can use the `/Q` to start MSI Afterburner sliently and then the application kills itself.

Example: `"C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" /Profile1 /Q`

Here the command applies `Profile 1` and quits silently.

Using this method is clean and quick to apply OC settings.

**Comment by amitxv** [comment]
Thanks, i was not aware of this.
